#!/usr/bin/env python3
"""
Environment Setup Script for Agentic Leak Detector
This script helps recreate the .env files on a new system
"""

import os
import sys
from pathlib import Path


def get_user_input(prompt, default="", required=False, hide_input=False):
    """Get user input with optional default value"""
    try:
        if hide_input:
            import getpass
            return getpass.getpass(f"{prompt} [{default}]: ").strip() or default
        else:
            user_input = input(f"{prompt} [{default}]: ").strip()
            if not user_input and required:
                print("  ⚠️  This field is required. Please try again.")
                return get_user_input(prompt, default, required, hide_input)
            return user_input or default
    except KeyboardInterrupt:
        print("\n❌ Setup cancelled by user")
        sys.exit(1)


def setup_backend_env():
    """Setup backend .env file"""
    print("\n" + "=" * 60)
    print("🔧 BACKEND ENVIRONMENT SETUP")
    print("=" * 60)
    
    backend_path = Path("backend")
    env_file = backend_path / ".env"
    
    # Check if .env already exists
    if env_file.exists():
        overwrite = input(f"\n⚠️  {env_file} already exists. Overwrite? (y/n): ").lower()
        if overwrite != "y":
            print("✅ Skipping backend .env setup")
            return
    
    print("\n📝 Enter backend configuration (press Enter to use defaults):")
    print("-" * 60)
    
    config = {
        "GEMINI_API_KEY": ("🔑 Gemini API Key", ""),
        "GEMINI_MODEL": ("📊 Gemini Model", "gemini-2.0-flash"),
        "GROQ_API_KEY": ("🔑 Groq API Key (optional)", ""),
        "GOOGLE_CLIENT_ID": ("🔐 Google Client ID", ""),
        "GOOGLE_CLIENT_SECRET": ("🔐 Google Client Secret", ""),
        "GOOGLE_REDIRECT_URI": ("🔗 Google Redirect URI", "http://localhost:8000/api/auth/callback"),
        "DATABASE_URL": ("💾 Database URL", "sqlite:///./finance_tracker.db"),
        "SECRET_KEY": ("🔑 Secret Key (JWT)", "your-super-secret-key-change-in-production"),
        "ALGORITHM": ("🔐 JWT Algorithm", "HS256"),
        "ACCESS_TOKEN_EXPIRE_MINUTES": ("⏱️  Access Token Expiry (minutes)", "30"),
        "RSA_PRIVATE_KEY": ("🔐 RSA Private Key", "-----BEGIN RSA PRIVATE KEY-----\\nYOUR_KEY_HERE\\n-----END RSA PRIVATE KEY-----"),
        "RSA_PUBLIC_KEY": ("🔐 RSA Public Key", "-----BEGIN PUBLIC KEY-----\\nYOUR_KEY_HERE\\n-----END PUBLIC KEY-----"),
        "ENVIRONMENT": ("🌍 Environment", "development"),
        "DEBUG": ("🐛 Debug Mode", "true"),
        "API_HOST": ("🌐 API Host", "0.0.0.0"),
        "API_PORT": ("🔌 API Port", "8000"),
        "EMAIL_SYNC_BATCH_SIZE": ("📧 Email Sync Batch Size", "50"),
        "EMAIL_SYNC_DAYS": ("📅 Email Sync Days", "30"),
        "FRONTEND_URL": ("🎨 Frontend URL", "http://localhost:5173"),
        "SMTP_HOST": ("📬 SMTP Host", "smtp.gmail.com"),
        "SMTP_PORT": ("📬 SMTP Port", "587"),
        "SMTP_USER": ("📬 SMTP Email Address", ""),
        "SMTP_PASSWORD": ("📬 SMTP App Password", ""),
        "FROM_EMAIL": ("📬 From Email Address", "noreply@finguard.com"),
    }
    
    env_content = "# Backend Environment Variables\n"
    env_content += "# Auto-generated by setup_env.py\n\n"
    
    for key, (prompt, default) in config.items():
        hide = "password" in key.lower() or "secret" in key.lower() or "key" in key.lower()
        value = get_user_input(f"  {prompt}", default, hide_input=hide)
        env_content += f"{key}={value}\n"
    
    # Write to file
    backend_path.mkdir(exist_ok=True)
    env_file.write_text(env_content)
    print(f"\n✅ Backend .env created at {env_file}")


def setup_frontend_env():
    """Setup frontend .env file"""
    print("\n" + "=" * 60)
    print("🎨 FRONTEND ENVIRONMENT SETUP")
    print("=" * 60)
    
    frontend_path = Path("frontend")
    env_file = frontend_path / ".env"
    
    # Check if .env already exists
    if env_file.exists():
        overwrite = input(f"\n⚠️  {env_file} already exists. Overwrite? (y/n): ").lower()
        if overwrite != "y":
            print("✅ Skipping frontend .env setup")
            return
    
    print("\n📝 Enter frontend configuration (press Enter to use defaults):")
    print("-" * 60)
    
    config = {
        "VITE_API_URL": ("🔗 Backend API URL", "http://localhost:8000"),
    }
    
    env_content = "# Frontend Environment Variables\n"
    env_content += "# Auto-generated by setup_env.py\n\n"
    
    for key, (prompt, default) in config.items():
        value = get_user_input(f"  {prompt}", default)
        env_content += f"{key}={value}\n"
    
    # Write to file
    frontend_path.mkdir(exist_ok=True)
    env_file.write_text(env_content)
    print(f"\n✅ Frontend .env created at {env_file}")


def verify_env_examples():
    """Verify that .env.example files are up to date"""
    print("\n" + "=" * 60)
    print("✅ ENVIRONMENT FILES VERIFICATION")
    print("=" * 60)
    
    backend_example = Path("backend/.env.example")
    frontend_example = Path("frontend/.env.example")
    
    if backend_example.exists():
        print(f"\n✔️  Found {backend_example}")
    else:
        print(f"\n❌ Missing {backend_example}")
    
    if frontend_example.exists():
        print(f"✔️  Found {frontend_example}")
    else:
        print(f"❌ Missing {frontend_example}")


def main():
    """Main setup function"""
    print("\n" + "=" * 60)
    print("🚀 AGENTIC LEAK DETECTOR - ENVIRONMENT SETUP")
    print("=" * 60)
    
    # Change to script directory
    script_dir = Path(__file__).parent
    os.chdir(script_dir)
    
    print("\nThis script will help you set up environment variables")
    print("for the Agentic Leak Detector project.")
    print("\nNote: Leave optional fields blank by pressing Enter")
    print("      without entering any value.")
    
    # Setup both environments
    setup_backend_env()
    setup_frontend_env()
    
    # Verify examples
    verify_env_examples()
    
    print("\n" + "=" * 60)
    print("✨ Setup Complete!")
    print("=" * 60)
    print("\n📋 Next steps:")
    print("  1. Install backend dependencies: pip install -r backend/requirements.txt")
    print("  2. Install frontend dependencies: cd frontend && npm install")
    print("  3. Start backend: cd backend && python main.py")
    print("  4. Start frontend: cd frontend && npm run dev")
    print("\n⚠️  Remember to:")
    print("  • Generate RSA keys for password encryption if needed")
    print("  • Add your Gemini API key for AI analysis")
    print("  • Configure Google OAuth if using OAuth authentication")
    print("  • Configure SMTP settings if using email features")
    print("\n")


if __name__ == "__main__":
    main()
